Fix: Move Disable Thermal GPU switch to RvGpu class
/home/runner/work/RvKernel-Manager/RvKernel-Manager/app/src/main/java/com/rvkernel/manager/RvSwitch.java:30: error: illegal start of expression

> Task :app:compileDebugJavaWithJavac FAILED
    private static void updateSwitchStates(RvmainBinding binding) {
    ^
/home/runner/work/RvKernel-Manager/RvKernel-Manager/app/src/main/java/com/rvkernel/manager/RvSwitch.java:46: error: illegal start of expression
    private static String getSchedAutoGroupValue() {
    ^
2 errors

Signed-off-by: Rve27 <rve27github@gmail.com>